// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR3ZSR_jbBddDbdIXibQk298VrGIY0yWA',
    appId: '1:337001769164:web:a70a0aa32e045840d2fa69',
    messagingSenderId: '337001769164',
    projectId: 'trolltungaarctictrout',
    authDomain: 'trolltungaarctictrout.firebaseapp.com',
    storageBucket: 'trolltungaarctictrout.firebasestorage.app',
    measurementId: 'G-JZ6ZJEW2HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGODw2eflOZTdhWVk7DWcuERz85ttNHPA',
    appId: '1:337001769164:android:d0837f6ddc3fa670d2fa69',
    messagingSenderId: '337001769164',
    projectId: 'trolltungaarctictrout',
    storageBucket: 'trolltungaarctictrout.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQVnv-qOTvFBfIP3yLLLsxE0cuzcgUB_w',
    appId: '1:337001769164:ios:aded299647b86784d2fa69',
    messagingSenderId: '337001769164',
    projectId: 'trolltungaarctictrout',
    storageBucket: 'trolltungaarctictrout.firebasestorage.app',
    iosBundleId: 'com.example.fjellfisk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQVnv-qOTvFBfIP3yLLLsxE0cuzcgUB_w',
    appId: '1:337001769164:ios:aded299647b86784d2fa69',
    messagingSenderId: '337001769164',
    projectId: 'trolltungaarctictrout',
    storageBucket: 'trolltungaarctictrout.firebasestorage.app',
    iosBundleId: 'com.example.fjellfisk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR3ZSR_jbBddDbdIXibQk298VrGIY0yWA',
    appId: '1:337001769164:web:6c7cbec241fa2016d2fa69',
    messagingSenderId: '337001769164',
    projectId: 'trolltungaarctictrout',
    authDomain: 'trolltungaarctictrout.firebaseapp.com',
    storageBucket: 'trolltungaarctictrout.firebasestorage.app',
    measurementId: 'G-ZM6ZHZ79X7',
  );
}
